[build]
  cmd = "go build -o tmp/chat ./cmd/chat"
  bin = "tmp/chat"
  include_ext = ["go"]
  include_dir = ["cmd/chat", "channel"]
  kill_delay = "200ms"
  rerun_delay = 200

[log]
  main_only = true
